# Generated by Django 4.2.7 on 2023-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='date_field',
            field=models.DateField(null=True),
        ),
    ]
