# Generated by Django 4.2.7 on 2023-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_studentmodel_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='big_integer_field',
            field=models.BigIntegerField(null=True),
        ),
    ]
