# Generated by Django 4.2.7 on 2023-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_studentmodel_big_integer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='binary_field',
            field=models.BinaryField(null=True),
        ),
    ]
