# Generated by Django 4.2.7 on 2023-12-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_studentmodel_binary_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='time_field',
            field=models.TimeField(null=True),
        ),
    ]
