# Generated by Django 4.2.7 on 2023-12-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_studentmodel_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='url_field',
            field=models.URLField(null=True),
        ),
    ]
