# Generated by Django 4.2.7 on 2023-12-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_studentmodel_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='uuid_field',
            field=models.UUIDField(null=True),
        ),
    ]
